# fly.toml app configuration file generated for ai-rag-app-aged-field-1899 on 2025-06-09T21:55:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-rag-app-aged-field-1899'
primary_region = 'ewr'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
PORT                         = "8080"
SPRING_SERVER_ADDRESS        = "0.0.0.0"
SPRING_DATASOURCE_URL        = "jdbc:${DATABASE_URL}"
SPRING_DATASOURCE_USERNAME   = "${DATABASE_USER}"
SPRING_DATASOURCE_PASSWORD   = "${DATABASE_PASSWORD}"
SPRING_AUTOCONFIGURE_EXCLUDE = "org.springframework.ai.autoconfigure.ollama.OllamaAutoConfiguration"
