server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource
    # Hikari connection pool configuration
    hikari:
      # Connection pool name
      pool-name: HikariCP
      # Minimum number of idle connections
      minimum-idle: 5
      # Maximum idle time for idle connections, default is 10 minutes
      idle-timeout: 600000
      # Maximum number of connections in the pool, default is 10
      maximum-pool-size: 10
      # Controls the default auto-commit behavior of connections returned from the pool, default: true
      auto-commit: true
      # Maximum lifetime of a connection in the pool, 0 means infinite, default is 30 minutes
      max-lifetime: 1800000
      # Database connection timeout, default is 30 seconds
      connection-timeout: 30000
      # Connection test query
      connection-test-query: SELECT 1

  ai:
    ollama:
      base-url: http://localhost:11434
      #      DeepSeek model configuration for ollama
      embedding:
        options:
          num-batch: 512
        model: nomic-embed-text
    openai:
      base-url: https://api.openai.com
      api-key: ${OPENAI_API_KEY}
      embedding-model: text-embedding-ada-002
    rag:
      embed: nomic-embed-text



redis:
  sdk:
    config:
      host: localhost
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
